### ISSUE TITLE
Do some research about different randomization algorithms

### ISSUE THREAD

**Issue by mnaray** [mnaray/sturdy-broccoli#4]
There are different ways of randomizing things with math. We might want to take it to the next level by becoming a bit more creative than just using the basic random number class in C#.

For this, someone should do some research about randomizing numbers and parameters and how to set limits to those.
Using a Mandelbrot or Julia set could be an interesting way of implementing randomization.

We might be able to use some of the methods which have been used in Minecraft as another example.

Just get creative with it, don't be lazy.

**Comment by mnaray** [comment]
This might be something worthy to check out:

https://www.youtube.com/watch?v=mBg74yR3ZiY&ab_channel=nicsure

**Comment by Tolv2** [comment]
Okay I'm on it but the Mandelbrot or Juliet sets have nothing to do with randomization? I'll try looking into procedural generation of the levels for now

**Comment by mnaray** [comment]
Yes, I thought we might be able to use them to create some sort of algorithm, but you're right. I did some research as well, and they really don't.

The procedural generation thing is the one used for generating Minecraft terrain, right?

**Comment by Tolv2** [comment]
Well procedural generation is an umbrella term; it literally just means creating the levels randomly as you play through them, MC does use a form of procedural generation as well as about a thousand other things.

Having read into some pcg algorithms, I think we should use some form of pseudo-random fractal algorithm (though I haven't found one for a map, so I'll probably just make my own thing) for the initial heightmap generation and then sand it down with a water droplet algorithm. If we want our levels large enough for them to include biomes we can use the Whittaker or Voronoi algorightms because they are super easy to code and come out looking very natural

pcg wiki is a godsend for this http://pcg.wikidot.com/category-pcg-algorithms
im goin to bed

**Comment by mnaray** [comment]
That wiki is actually quite nice to have.

This is some sort of blog where someone talks about creating a procedurally generated platformer.
https://www.gamedeveloper.com/design/how-to-make-insane-procedural-platformer-levels
